module.exports = {
  UserController: require('./userController'),
  RoleController: require('./roleController'),
  PermissionController: require('./permissionController'),
  AuthzController: require('./authzController'),
  LendingLocationController: require('./lendingLocationController'),
  OpeningHourController: require('./openingHourController'),
  ManufacturerController: require('./manufacturerController'),
  AssetCategoryController: require('./assetCategoryController'),
  AssetModelController: require('./assetModelController'),
  AssetInstanceController: require('./assetInstanceController'),
  StorageLocationController: require('./storageLocationController'),
  AssetAttachmentController: require('./assetAttachmentController'),
  AssetMaintenanceController: require('./assetMaintenanceController'),
  LoanEventController: require('./loanEventController'),
  OpeningExceptionController: require('./openingExceptionController'),
  CustomFieldDefinitionController: require('./customFieldDefinitionController'),
  CustomFieldValueController: require('./customFieldValueController'),
  LoanController: require('./loanController'),
  LoanItemController: require('./loanItemController'),
  LoanSignatureController: require('./loanSignatureController'),
  AuditLogController: require('./auditLogController'),
};
