module.exports = {
  UserController: require('./UserController'),
  RoleController: require('./RoleController'),
  PermissionController: require('./PermissionController'),
  AuthzController: require('./AuthzController'),
  LendingLocationController: require('./LendingLocationController'),
  OpeningHourController: require('./OpeningHourController'),
  ManufacturerController: require('./ManufacturerController'),
  AssetCategoryController: require('./AssetCategoryController'),
  AssetModelController: require('./AssetModelController'),
  AssetInstanceController: require('./AssetInstanceController'),
  StorageLocationController: require('./StorageLocationController'),
  AssetAttachmentController: require('./AssetAttachmentController'),
  AssetMaintenanceController: require('./AssetMaintenanceController'),
  LoanEventController: require('./LoanEventController'),
  OpeningExceptionController: require('./OpeningExceptionController'),
  CustomFieldDefinitionController: require('./CustomFieldDefinitionController'),
  CustomFieldValueController: require('./CustomFieldValueController'),
  LoanController: require('./LoanController'),
  LoanItemController: require('./LoanItemController'),
  LoanSignatureController: require('./LoanSignatureController'),
  AuditLogController: require('./AuditLogController'),
};
