module.exports = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    route: '/dashboard',
    icon: 'dashboard',
    permissions: [],
    scope: 'both',
    order: 10,
  },
  {
    id: 'assets',
    label: 'Assets',
    route: '/assets',
    icon: 'assets',
    permissions: ['loan.create', 'loan.manage', 'inventory.manage'],
    scope: 'both',
    order: 20,
    children: [
      { id: 'assets.list', label: 'Alle Assets', route: '/assets', icon: 'list', permissions: ['loan.create', 'loan.manage', 'inventory.manage'], scope: 'both', order: 10 },
      { id: 'assets.reserve', label: 'Reservieren', route: '/assets', icon: 'reserve', permissions: ['loan.create'], scope: 'ausleihe', order: 20 },
    ],
  },
  {
    id: 'reservations',
    label: 'Warenkorb',
    route: '/cart',
    icon: 'reservations',
    permissions: ['loan.create'],
    scope: 'both',
    order: 30,
  },
  {
    id: 'loans',
    label: 'Ausleihen',
    route: '/loans',
    icon: 'loans',
    permissions: ['loan.manage'],
    scope: 'ausleihe',
    order: 40,
  },
  {
    id: 'admin',
    label: 'Admin',
    route: '/admin/assets',
    icon: 'admin',
    permissions: ['inventory.manage', 'openinghours.manage', 'loan.manage', 'users.manage', 'roles.manage', 'permissions.manage', 'customfields.manage', 'audit.view', 'system.admin', 'lendinglocations.manage'],
    scope: 'both',
    order: 50,
    children: [
      { id: 'admin.assets', label: 'Assets', route: '/admin/assets', icon: 'assets', permissions: ['inventory.manage'], scope: 'ausleihe', order: 10 },
      { id: 'admin.models', label: 'Modelle', route: '/admin/asset-models', icon: 'models', permissions: ['inventory.manage'], scope: 'ausleihe', order: 20 },
      { id: 'admin.customFields', label: 'Custom Fields', route: '/admin/custom-fields', icon: 'custom', permissions: ['customfields.manage'], scope: 'global', order: 30 },
      { id: 'admin.users', label: 'Benutzer', route: '/admin/users', icon: 'users', permissions: ['users.manage'], scope: 'global', order: 40 },
      { id: 'admin.config', label: 'Konfiguration', route: '/admin/opening-hours', icon: 'config', permissions: ['openinghours.manage'], scope: 'ausleihe', order: 50 },
    ],
  },
  {
    id: 'system',
    label: 'System',
    route: '/system/lending-locations',
    icon: 'system',
    permissions: ['system.admin', 'audit.view', 'lendinglocations.manage', 'system.auth.manage'],
    scope: 'global',
    order: 60,
    children: [
      { id: 'system.locations', label: 'Ausleihstellen', route: '/system/lending-locations', icon: 'locations', permissions: ['system.admin', 'lendinglocations.manage'], scope: 'global', order: 10 },
      { id: 'system.audit', label: 'Audit Log', route: '/system/audit-log', icon: 'audit', permissions: ['system.admin', 'audit.view'], scope: 'global', order: 20 },
      { id: 'system.authConfig', label: 'Auth Config', route: '/system/auth-config', icon: 'auth', permissions: ['system.auth.manage'], scope: 'global', order: 25 },
      { id: 'system.reports', label: 'Reports', route: '/system/reports', icon: 'reports', permissions: ['system.admin'], scope: 'global', order: 30 },
    ],
  },
];
