module.exports = function registerRbacRoutes(routeContext) {
  const {
    router,
    middlewareStacks,
    middlewares,
    loaders,
    controllers,
    validations,
    helpers,
  } = routeContext;

  router.get(
    '/admin/lending-user-roles',
    ...middlewareStacks.authenticatedLendingContext(),
    helpers.requireLendingRoleManagement,
    controllers.lendingUserRoleAdminController.index.bind(controllers.lendingUserRoleAdminController)
  );
  router.post(
    '/admin/lending-user-roles/:id/roles/assign',
    ...middlewareStacks.authenticatedLendingContext(),
    helpers.requireLendingRoleManagement,
    controllers.lendingUserRoleAdminController.assign.bind(controllers.lendingUserRoleAdminController)
  );
  router.post(
    '/admin/lending-user-roles/:id/roles/:roleId/revoke',
    ...middlewareStacks.authenticatedLendingContext(),
    helpers.requireLendingRoleManagement,
    controllers.lendingUserRoleAdminController.revoke.bind(controllers.lendingUserRoleAdminController)
  );

  router.get(
    '/admin/custom-fields',
    ...middlewareStacks.customFieldsGlobal(),
    controllers.customFieldAdminController.index.bind(controllers.customFieldAdminController)
  );
  router.get(
    '/admin/custom-fields/new',
    ...middlewareStacks.customFieldsGlobal(),
    loaders.loadCustomFieldFormData,
    controllers.customFieldAdminController.new.bind(controllers.customFieldAdminController)
  );
  router.post(
    '/admin/custom-fields',
    ...middlewareStacks.customFieldsGlobal(),
    loaders.loadCustomFieldFormData,
    validations.customFieldCreateValidation,
    middlewares.validate('admin/custom-fields/new'),
    controllers.customFieldAdminController.create.bind(controllers.customFieldAdminController)
  );
  router.get(
    '/admin/custom-fields/:id/edit',
    ...middlewareStacks.customFieldsGlobal(),
    loaders.loadCustomFieldFormData,
    controllers.customFieldAdminController.edit.bind(controllers.customFieldAdminController)
  );
  router.post(
    '/admin/custom-fields/:id',
    ...middlewareStacks.customFieldsGlobal(),
    loaders.loadCustomFieldFormData,
    validations.customFieldUpdateValidation,
    middlewares.validate('admin/custom-fields/edit'),
    controllers.customFieldAdminController.update.bind(controllers.customFieldAdminController)
  );
  router.post(
    '/admin/custom-fields/:id/delete',
    ...middlewareStacks.customFieldsGlobal(),
    controllers.customFieldAdminController.remove.bind(controllers.customFieldAdminController)
  );
  router.post(
    '/admin/custom-fields/:id/restore',
    ...middlewareStacks.customFieldsGlobal(),
    controllers.customFieldAdminController.restore.bind(controllers.customFieldAdminController)
  );

  router.get(
    '/admin/users',
    ...middlewareStacks.usersGlobal(),
    controllers.userAdminController.index.bind(controllers.userAdminController)
  );
  router.get(
    '/admin/users/new',
    ...middlewareStacks.usersGlobal(),
    loaders.loadAllRoles,
    controllers.userAdminController.new.bind(controllers.userAdminController)
  );
  router.post(
    '/admin/users',
    ...middlewareStacks.usersGlobal(),
    loaders.loadAllRoles,
    validations.userCreateValidation,
    middlewares.validate('admin/users/new'),
    controllers.userAdminController.create.bind(controllers.userAdminController)
  );
  router.post(
    '/admin/users/bulk',
    ...middlewareStacks.usersGlobal(),
    controllers.userAdminController.bulk.bind(controllers.userAdminController)
  );
  router.get(
    '/admin/users/:id',
    ...middlewareStacks.usersGlobal(),
    controllers.userAdminController.show.bind(controllers.userAdminController)
  );
  router.post(
    '/admin/users/:id/roles',
    ...middlewareStacks.usersGlobal(),
    controllers.userAdminController.assignRoleFromDetail.bind(controllers.userAdminController)
  );
  router.get(
    '/admin/users/:id/edit',
    ...middlewareStacks.usersGlobal(),
    loaders.loadUserEditData,
    controllers.userAdminController.edit.bind(controllers.userAdminController)
  );
  router.post(
    '/admin/users/:id',
    ...middlewareStacks.usersGlobal(),
    loaders.loadUserEditData,
    validations.userUpdateValidation,
    middlewares.validate('admin/users/edit'),
    controllers.userAdminController.update.bind(controllers.userAdminController)
  );
  router.post(
    '/admin/users/:id/delete',
    ...middlewareStacks.usersGlobal(),
    controllers.userAdminController.remove.bind(controllers.userAdminController)
  );
  router.post(
    '/admin/users/:id/restore',
    ...middlewareStacks.usersGlobal(),
    controllers.userAdminController.restore.bind(controllers.userAdminController)
  );

  router.get(
    '/admin/roles',
    ...middlewareStacks.rolesGlobal(),
    controllers.roleAdminController.index.bind(controllers.roleAdminController)
  );
  router.get(
    '/admin/roles/new',
    ...middlewareStacks.rolesGlobal(),
    loaders.loadAllPermissions,
    controllers.roleAdminController.new.bind(controllers.roleAdminController)
  );
  router.post(
    '/admin/roles',
    ...middlewareStacks.rolesGlobal(),
    loaders.loadAllPermissions,
    validations.roleValidation,
    middlewares.validate('admin/roles/new'),
    controllers.roleAdminController.create.bind(controllers.roleAdminController)
  );
  router.get(
    '/admin/roles/:id/edit',
    ...middlewareStacks.rolesGlobal(),
    loaders.loadRoleEditData,
    controllers.roleAdminController.edit.bind(controllers.roleAdminController)
  );
  router.post(
    '/admin/roles/:id',
    ...middlewareStacks.rolesGlobal(),
    loaders.loadRoleEditData,
    validations.roleValidation,
    middlewares.validate('admin/roles/edit'),
    controllers.roleAdminController.update.bind(controllers.roleAdminController)
  );
  router.post(
    '/admin/roles/:id/delete',
    ...middlewareStacks.rolesGlobal(),
    controllers.roleAdminController.remove.bind(controllers.roleAdminController)
  );
  router.post(
    '/admin/roles/:id/restore',
    ...middlewareStacks.rolesGlobal(),
    controllers.roleAdminController.restore.bind(controllers.roleAdminController)
  );

  router.get(
    '/admin/permissions',
    ...middlewareStacks.permissionsGlobal(),
    controllers.permissionAdminController.index.bind(controllers.permissionAdminController)
  );
  router.get(
    '/admin/permissions/new',
    ...middlewareStacks.permissionsGlobal(),
    controllers.permissionAdminController.new.bind(controllers.permissionAdminController)
  );
  router.post(
    '/admin/permissions',
    ...middlewareStacks.permissionsGlobal(),
    validations.permissionValidation,
    middlewares.validate('admin/permissions/new'),
    controllers.permissionAdminController.create.bind(controllers.permissionAdminController)
  );
  router.get(
    '/admin/permissions/:id/edit',
    ...middlewareStacks.permissionsGlobal(),
    controllers.permissionAdminController.edit.bind(controllers.permissionAdminController)
  );
  router.post(
    '/admin/permissions/:id',
    ...middlewareStacks.permissionsGlobal(),
    validations.permissionValidation,
    middlewares.validate('admin/permissions/edit'),
    controllers.permissionAdminController.update.bind(controllers.permissionAdminController)
  );
  router.post(
    '/admin/permissions/:id/delete',
    ...middlewareStacks.permissionsGlobal(),
    controllers.permissionAdminController.remove.bind(controllers.permissionAdminController)
  );
};
