module.exports = function buildComponents({ ErrorResponse }) {
  return {
    securitySchemes: {
      SessionAuth: {
        type: 'apiKey',
        in: 'cookie',
        name: 'sid',
        description:
          'Session-Cookie nach Login. Hinweis: Der Cookie-Name kann per SESSION_COOKIE_NAME angepasst werden.',
      },
      CsrfToken: {
        type: 'apiKey',
        in: 'header',
        name: 'x-csrf-token',
        description:
          'Für nicht-GET Requests erforderlich (Double-Submit CSRF Schutz).',
      },
    },
    schemas: {
      ErrorResponse,
      User: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          username: { type: 'string' },
          email: { type: 'string' },
          firstName: { type: 'string', nullable: true },
          lastName: { type: 'string', nullable: true },
          isActive: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      Role: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          description: { type: 'string', nullable: true },
          scope: { type: 'string', enum: ['global', 'ausleihe', 'both'] },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      Permission: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          key: { type: 'string' },
          description: { type: 'string', nullable: true },
          scope: { type: 'string', enum: ['global', 'ausleihe', 'both'] },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      LendingLocation: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          description: { type: 'string', nullable: true },
          contactEmail: { type: 'string', nullable: true },
          isActive: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      OpeningHour: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          lendingLocationId: { type: 'string', format: 'uuid' },
          dayOfWeek: { type: 'string', enum: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'] },
          openTime: { type: 'string', nullable: true },
          closeTime: { type: 'string', nullable: true },
          isClosed: { type: 'boolean' },
          validFrom: { type: 'string', format: 'date', nullable: true },
          validTo: { type: 'string', format: 'date', nullable: true },
          isSpecial: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      OpeningException: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          lendingLocationId: { type: 'string', format: 'uuid' },
          date: { type: 'string', format: 'date' },
          openTime: { type: 'string', nullable: true },
          closeTime: { type: 'string', nullable: true },
          isClosed: { type: 'boolean' },
          reason: { type: 'string', nullable: true },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      Manufacturer: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          website: { type: 'string', nullable: true },
          isActive: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      AssetCategory: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          description: { type: 'string', nullable: true },
          isActive: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      AssetModel: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          manufacturerId: { type: 'string', format: 'uuid' },
          categoryId: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          description: { type: 'string', nullable: true },
          technicalDescription: { type: 'string', nullable: true },
          imageUrl: { type: 'string', nullable: true },
          isActive: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      AssetInstance: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          lendingLocationId: { type: 'string', format: 'uuid' },
          assetModelId: { type: 'string', format: 'uuid' },
          storageLocationId: { type: 'string', format: 'uuid', nullable: true },
          inventoryNumber: { type: 'string' },
          serialNumber: { type: 'string', nullable: true },
          condition: { type: 'string', enum: ['new', 'good', 'fair', 'damaged', 'lost'] },
          isActive: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      StorageLocation: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          lendingLocationId: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          description: { type: 'string', nullable: true },
          isActive: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      AssetAttachment: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          assetModelId: { type: 'string', format: 'uuid', nullable: true },
          assetId: { type: 'string', format: 'uuid', nullable: true },
          kind: { type: 'string', enum: ['image', 'manual', 'document', 'other'] },
          url: { type: 'string' },
          title: { type: 'string', nullable: true },
          isPrimary: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      AssetMaintenance: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          assetId: { type: 'string', format: 'uuid' },
          status: { type: 'string', enum: ['reported', 'in_progress', 'completed', 'cancelled'] },
          reportedAt: { type: 'string', format: 'date-time' },
          completedAt: { type: 'string', format: 'date-time', nullable: true },
          notes: { type: 'string', nullable: true },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      CustomFieldDefinition: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          scope: { type: 'string', enum: ['asset_model', 'lending_location'] },
          assetModelId: { type: 'string', format: 'uuid', nullable: true },
          lendingLocationId: { type: 'string', format: 'uuid', nullable: true },
          key: { type: 'string' },
          label: { type: 'string' },
          type: { type: 'string', enum: ['string', 'text', 'number', 'boolean', 'date', 'enum'] },
          enumValues: { type: 'array', items: { type: 'string' }, nullable: true },
          required: { type: 'boolean' },
          defaultValue: { type: 'string', nullable: true },
          isActive: { type: 'boolean' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      CustomFieldValue: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          customFieldDefinitionId: { type: 'string', format: 'uuid' },
          assetInstanceId: { type: 'string', format: 'uuid' },
          valueString: { type: 'string', nullable: true },
          valueNumber: { type: 'number', nullable: true },
          valueBoolean: { type: 'boolean', nullable: true },
          valueDate: { type: 'string', format: 'date', nullable: true },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      Loan: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          userId: { type: 'string', format: 'uuid' },
          lendingLocationId: { type: 'string', format: 'uuid' },
          status: { type: 'string', enum: ['reserved', 'cancelled', 'handed_over', 'returned', 'overdue'] },
          reservedFrom: { type: 'string', format: 'date-time' },
          reservedUntil: { type: 'string', format: 'date-time' },
          handedOverAt: { type: 'string', format: 'date-time', nullable: true },
          returnedAt: { type: 'string', format: 'date-time', nullable: true },
          notes: { type: 'string', nullable: true },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      LoanItem: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          loanId: { type: 'string', format: 'uuid' },
          assetId: { type: 'string', format: 'uuid' },
          status: { type: 'string', enum: ['reserved', 'handed_over', 'returned', 'lost', 'damaged'] },
          conditionOnHandover: { type: 'string', enum: ['new', 'good', 'fair', 'damaged', 'lost'], nullable: true },
          conditionOnReturn: { type: 'string', enum: ['new', 'good', 'fair', 'damaged', 'lost'], nullable: true },
          handedOverAt: { type: 'string', format: 'date-time', nullable: true },
          returnedAt: { type: 'string', format: 'date-time', nullable: true },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          deletedAt: { type: 'string', format: 'date-time', nullable: true },
        },
      },
      LoanSignature: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          loanId: { type: 'string', format: 'uuid' },
          userId: { type: 'string', format: 'uuid' },
          signatureType: { type: 'string', enum: ['handed_over', 'returned'] },
          signatureData: { type: 'string', nullable: true },
          signedAt: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      LoanEvent: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          loanId: { type: 'string', format: 'uuid' },
          userId: { type: 'string', format: 'uuid', nullable: true },
          type: { type: 'string' },
          occurredAt: { type: 'string', format: 'date-time' },
          note: { type: 'string', nullable: true },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      AuditLog: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          userId: { type: 'string', format: 'uuid', nullable: true },
          action: { type: 'string' },
          entity: { type: 'string' },
          entityId: { type: 'string', format: 'uuid' },
          metadata: { type: 'object', nullable: true },
          createdAt: { type: 'string', format: 'date-time' },
        },
      },
    },
  };
};
