// Generated file: edit source builders and regenerate; do not hand-edit.
module.exports = function buildPaths(builders) {
  const { okResponse, withListParams, withIdempotency, withIdempotencyAndIfMatch, errorResponses } = builders;
  // Do not hand-edit generated sections; update source builders instead.
  return {
    '/users': {
      get: {
        tags: ['Users'],
        summary: 'List users',
        description: 'Returns all users with roles and permissions',
        parameters: withListParams([{ name: 'isActive', in: 'query', schema: { type: 'boolean' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/User' } }), ...errorResponses },
      },
      post: {
        tags: ['Users'],
        summary: 'Create user',
        description: 'Creates a new user',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/User' }), ...errorResponses },
      },
    },
    '/users/search': {
      get: {
        tags: ['Users'],
        summary: 'Search users',
        description: 'Search users by query or fields',
        parameters: withListParams([
          { name: 'q', in: 'query', schema: { type: 'string' } },
          { name: 'username', in: 'query', schema: { type: 'string' } },
          { name: 'email', in: 'query', schema: { type: 'string' } },
          { name: 'firstName', in: 'query', schema: { type: 'string' } },
          { name: 'lastName', in: 'query', schema: { type: 'string' } },
          { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/User' } }), ...errorResponses },
      },
    },
    '/users/username/{username}': {
      get: {
        tags: ['Users'],
        summary: 'Get user by username',
        description: 'Fetch a user by username',
        parameters: [
          { name: 'username', in: 'path', required: true, schema: { type: 'string' } },
          { name: 'withPassword', in: 'query', schema: { type: 'boolean' } },
        ],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/User' }), ...errorResponses },
      },
    },
    '/users/{id}': {
      get: {
        tags: ['Users'],
        summary: 'Get user',
        description: 'Fetch a user by id',
        parameters: [
          { name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
          { name: 'withPassword', in: 'query', schema: { type: 'boolean' } },
        ],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/User' }), ...errorResponses },
      },
      put: {
        tags: ['Users'],
        summary: 'Update user',
        description: 'Updates a user by id',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/User' }), ...errorResponses },
      },
      delete: {
        tags: ['Users'],
        summary: 'Delete user',
        description: 'Deletes a user by id',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/users/{id}/password': {
      put: {
        tags: ['Users'],
        summary: 'Set password',
        description: 'Updates user password',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { password: { type: 'string' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/User' }), ...errorResponses },
      },
    },
    '/users/{id}/active': {
      put: {
        tags: ['Users'],
        summary: 'Set active',
        description: 'Activate or deactivate a user',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { isActive: { type: 'boolean' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/User' }), ...errorResponses },
      },
    },
    '/users/{id}/roles': {
      get: {
        tags: ['Users'],
        summary: 'List user roles',
        description: 'Returns roles for a user',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { type: 'object' } }), ...errorResponses },
      },
      post: {
        tags: ['Users'],
        summary: 'Assign role',
        description: 'Assigns a role to a user',
        parameters: withIdempotency([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { roleId: { type: 'string', format: 'uuid' }, lendingLocationId: { type: 'string', format: 'uuid', nullable: true } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
      delete: {
        tags: ['Users'],
        summary: 'Revoke role',
        description: 'Revokes a role from a user',
        parameters: withIdempotency([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { roleId: { type: 'string', format: 'uuid' }, lendingLocationId: { type: 'string', format: 'uuid', nullable: true } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/roles': {
      get: {
        tags: ['Roles'],
        summary: 'List roles',
        description: 'Returns all roles',
        parameters: withListParams(),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/Role' } }), ...errorResponses },
      },
      post: {
        tags: ['Roles'],
        summary: 'Create role',
        description: 'Creates a role',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Role' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Role' }), ...errorResponses },
      },
    },
    '/roles/search': {
      get: {
        tags: ['Roles'],
        summary: 'Search roles',
        description: 'Search roles by query or fields',
        parameters: withListParams([
          { name: 'q', in: 'query', schema: { type: 'string' } },
          { name: 'name', in: 'query', schema: { type: 'string' } },
          { name: 'scope', in: 'query', schema: { type: 'string' } },
          { name: 'description', in: 'query', schema: { type: 'string' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/Role' } }), ...errorResponses },
      },
    },
    '/roles/{id}': {
      get: {
        tags: ['Roles'],
        summary: 'Get role',
        description: 'Fetch a role by id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Role' }), ...errorResponses },
      },
      put: {
        tags: ['Roles'],
        summary: 'Update role',
        description: 'Updates a role by id',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Role' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Role' }), ...errorResponses },
      },
      delete: {
        tags: ['Roles'],
        summary: 'Delete role',
        description: 'Deletes a role by id',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/roles/{id}/permissions': {
      post: {
        tags: ['Roles'],
        summary: 'Add permission',
        description: 'Adds a permission to a role',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { permissionId: { type: 'string', format: 'uuid' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
      delete: {
        tags: ['Roles'],
        summary: 'Remove permission',
        description: 'Removes a permission from a role',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { permissionId: { type: 'string', format: 'uuid' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/permissions': {
      get: {
        tags: ['Permissions'],
        summary: 'List permissions',
        description: 'Returns all permissions',
        parameters: withListParams(),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/Permission' } }), ...errorResponses },
      },
      post: {
        tags: ['Permissions'],
        summary: 'Create permission',
        description: 'Creates a permission',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Permission' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Permission' }), ...errorResponses },
      },
    },
    '/permissions/search': {
      get: {
        tags: ['Permissions'],
        summary: 'Search permissions',
        description: 'Search permissions by query or fields',
        parameters: withListParams([
          { name: 'q', in: 'query', schema: { type: 'string' } },
          { name: 'key', in: 'query', schema: { type: 'string' } },
          { name: 'scope', in: 'query', schema: { type: 'string' } },
          { name: 'description', in: 'query', schema: { type: 'string' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/Permission' } }), ...errorResponses },
      },
    },
    '/permissions/key/{key}': {
      get: {
        tags: ['Permissions'],
        summary: 'Get permission by key',
        description: 'Fetch a permission by key',
        parameters: [{ name: 'key', in: 'path', required: true, schema: { type: 'string' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Permission' }), ...errorResponses },
      },
    },
    '/permissions/{id}': {
      get: {
        tags: ['Permissions'],
        summary: 'Get permission',
        description: 'Fetch a permission by id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Permission' }), ...errorResponses },
      },
      put: {
        tags: ['Permissions'],
        summary: 'Update permission',
        description: 'Updates a permission by id',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Permission' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Permission' }), ...errorResponses },
      },
      delete: {
        tags: ['Permissions'],
        summary: 'Delete permission',
        description: 'Deletes a permission by id',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/lending-locations': {
      get: {
        tags: ['LendingLocations'],
        summary: 'List lending locations',
        description: 'Returns all lending locations',
        parameters: withListParams([{ name: 'isActive', in: 'query', schema: { type: 'boolean' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/LendingLocation' } }), ...errorResponses },
      },
      post: {
        tags: ['LendingLocations'],
        summary: 'Create lending location',
        description: 'Creates a lending location',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LendingLocation' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LendingLocation' }), ...errorResponses },
      },
    },
    '/lending-locations/{id}': {
      get: {
        tags: ['LendingLocations'],
        summary: 'Get lending location',
        description: 'Fetch a lending location by id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LendingLocation' }), ...errorResponses },
      },
      put: {
        tags: ['LendingLocations'],
        summary: 'Update lending location',
        description: 'Updates a lending location by id',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LendingLocation' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LendingLocation' }), ...errorResponses },
      },
      delete: {
        tags: ['LendingLocations'],
        summary: 'Delete lending location',
        description: 'Deletes a lending location by id',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/lending-locations/{id}/active': {
      put: {
        tags: ['LendingLocations'],
        summary: 'Set active',
        description: 'Activate or deactivate a lending location',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { isActive: { type: 'boolean' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LendingLocation' }), ...errorResponses },
      },
    },
    '/opening-hours/regular': {
      post: {
        tags: ['OpeningHours'],
        summary: 'Set regular hours',
        description: 'Creates or updates regular opening hours',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/OpeningHour' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/OpeningHour' }), ...errorResponses },
      },
    },
    '/opening-hours/regular/{lendingLocationId}': {
      get: {
        tags: ['OpeningHours'],
        summary: 'List regular hours',
        description: 'Lists regular opening hours for a location',
        parameters: withListParams([{ name: 'lendingLocationId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/OpeningHour' } }), ...errorResponses },
      },
    },
    '/opening-hours/regular/{lendingLocationId}/{dayOfWeek}': {
      delete: {
        tags: ['OpeningHours'],
        summary: 'Delete regular hours',
        description: 'Deletes regular opening hours for a day',
        parameters: withIdempotency([
          { name: 'lendingLocationId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
          { name: 'dayOfWeek', in: 'path', required: true, schema: { type: 'string' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/opening-hours/exception': {
      post: {
        tags: ['OpeningHours'],
        summary: 'Set exception',
        description: 'Creates or updates an opening exception',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/OpeningException' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/OpeningException' }), ...errorResponses },
      },
    },
    '/opening-hours/exception/{lendingLocationId}': {
      get: {
        tags: ['OpeningHours'],
        summary: 'List exceptions',
        description: 'Lists opening exceptions for a location',
        parameters: withListParams([{ name: 'lendingLocationId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/OpeningException' } }), ...errorResponses },
      },
    },
    '/opening-hours/exception/{lendingLocationId}/{date}': {
      delete: {
        tags: ['OpeningHours'],
        summary: 'Delete exception',
        description: 'Deletes an opening exception',
        parameters: withIdempotency([
          { name: 'lendingLocationId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
          { name: 'date', in: 'path', required: true, schema: { type: 'string', format: 'date' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/opening-exceptions': {
      get: {
        tags: ['OpeningExceptions'],
        summary: 'List opening exceptions',
        description: 'Returns opening exceptions',
        parameters: withListParams([
          { name: 'lendingLocationId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'date', in: 'query', schema: { type: 'string', format: 'date' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/OpeningException' } }), ...errorResponses },
      },
      post: {
        tags: ['OpeningExceptions'],
        summary: 'Create opening exception',
        description: 'Creates an opening exception',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/OpeningException' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/OpeningException' }), ...errorResponses },
      },
    },
    '/opening-exceptions/{id}': {
      get: {
        tags: ['OpeningExceptions'],
        summary: 'Get opening exception',
        description: 'Fetch an opening exception by id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/OpeningException' }), ...errorResponses },
      },
      put: {
        tags: ['OpeningExceptions'],
        summary: 'Update opening exception',
        description: 'Updates an opening exception',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/OpeningException' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/OpeningException' }), ...errorResponses },
      },
      delete: {
        tags: ['OpeningExceptions'],
        summary: 'Delete opening exception',
        description: 'Deletes an opening exception',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/manufacturers': {
      get: {
        tags: ['Manufacturers'],
        summary: 'List manufacturers',
        description: 'Returns all manufacturers',
        parameters: withListParams([{ name: 'isActive', in: 'query', schema: { type: 'boolean' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/Manufacturer' } }), ...errorResponses },
      },
      post: {
        tags: ['Manufacturers'],
        summary: 'Create manufacturer',
        description: 'Creates a manufacturer',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Manufacturer' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Manufacturer' }), ...errorResponses },
      },
    },
    '/manufacturers/{id}': {
      get: {
        tags: ['Manufacturers'],
        summary: 'Get manufacturer',
        description: 'Fetch a manufacturer by id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Manufacturer' }), ...errorResponses },
      },
      put: {
        tags: ['Manufacturers'],
        summary: 'Update manufacturer',
        description: 'Updates a manufacturer',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Manufacturer' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Manufacturer' }), ...errorResponses },
      },
      delete: {
        tags: ['Manufacturers'],
        summary: 'Delete manufacturer',
        description: 'Deletes a manufacturer',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/asset-categories': {
      get: {
        tags: ['AssetCategories'],
        summary: 'List categories',
        description: 'Returns all asset categories',
        parameters: withListParams([{ name: 'isActive', in: 'query', schema: { type: 'boolean' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/AssetCategory' } }), ...errorResponses },
      },
      post: {
        tags: ['AssetCategories'],
        summary: 'Create category',
        description: 'Creates an asset category',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetCategory' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetCategory' }), ...errorResponses },
      },
    },
    '/asset-categories/{id}': {
      get: {
        tags: ['AssetCategories'],
        summary: 'Get category',
        description: 'Fetch an asset category',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetCategory' }), ...errorResponses },
      },
      put: {
        tags: ['AssetCategories'],
        summary: 'Update category',
        description: 'Updates an asset category',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetCategory' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetCategory' }), ...errorResponses },
      },
      delete: {
        tags: ['AssetCategories'],
        summary: 'Delete category',
        description: 'Deletes an asset category',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/asset-categories/{id}/active': {
      put: {
        tags: ['AssetCategories'],
        summary: 'Set active',
        description: 'Activate or deactivate a category',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { isActive: { type: 'boolean' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetCategory' }), ...errorResponses },
      },
    },
    '/asset-models': {
      get: {
        tags: ['AssetModels'],
        summary: 'List asset models',
        description: 'Returns all asset models',
        parameters: withListParams([
          { name: 'manufacturerId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'categoryId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/AssetModel' } }), ...errorResponses },
      },
      post: {
        tags: ['AssetModels'],
        summary: 'Create asset model',
        description: 'Creates an asset model',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetModel' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetModel' }), ...errorResponses },
      },
    },
    '/asset-models/{id}': {
      get: {
        tags: ['AssetModels'],
        summary: 'Get asset model',
        description: 'Fetch an asset model',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetModel' }), ...errorResponses },
      },
      put: {
        tags: ['AssetModels'],
        summary: 'Update asset model',
        description: 'Updates an asset model',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetModel' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetModel' }), ...errorResponses },
      },
      delete: {
        tags: ['AssetModels'],
        summary: 'Delete asset model',
        description: 'Deletes an asset model',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/assets': {
      get: {
        tags: ['Assets'],
        summary: 'List assets',
        description: 'Returns all assets',
        parameters: withListParams([
          { name: 'lendingLocationId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'assetModelId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/AssetInstance' } }), ...errorResponses },
      },
      post: {
        tags: ['Assets'],
        summary: 'Create asset',
        description: 'Creates an asset instance',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetInstance' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetInstance' }), ...errorResponses },
      },
    },
    '/assets/search': {
      get: {
        tags: ['Assets'],
        summary: 'Search assets',
        description: 'Search assets by query or fields',
        parameters: withListParams([
          { name: 'q', in: 'query', schema: { type: 'string' } },
          { name: 'inventoryNumber', in: 'query', schema: { type: 'string' } },
          { name: 'serialNumber', in: 'query', schema: { type: 'string' } },
          { name: 'name', in: 'query', schema: { type: 'string' } },
          { name: 'description', in: 'query', schema: { type: 'string' } },
          { name: 'manufacturer', in: 'query', schema: { type: 'string' } },
          { name: 'lendingLocationId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'assetModelId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/AssetInstance' } }), ...errorResponses },
      },
    },
    '/assets/{id}': {
      get: {
        tags: ['Assets'],
        summary: 'Get asset',
        description: 'Fetch an asset by id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetInstance' }), ...errorResponses },
      },
      put: {
        tags: ['Assets'],
        summary: 'Update asset',
        description: 'Updates an asset',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetInstance' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetInstance' }), ...errorResponses },
      },
      delete: {
        tags: ['Assets'],
        summary: 'Delete asset',
        description: 'Deletes an asset',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/assets/{id}/storage-location': {
      put: {
        tags: ['Assets'],
        summary: 'Move asset',
        description: 'Moves an asset to a storage location',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { storageLocationId: { type: 'string', format: 'uuid' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetInstance' }), ...errorResponses },
      },
    },
    '/assets/{id}/condition': {
      put: {
        tags: ['Assets'],
        summary: 'Set condition',
        description: 'Updates asset condition',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { condition: { type: 'string' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetInstance' }), ...errorResponses },
      },
    },
    '/assets/{id}/active': {
      put: {
        tags: ['Assets'],
        summary: 'Set active',
        description: 'Activate or deactivate asset',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { isActive: { type: 'boolean' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetInstance' }), ...errorResponses },
      },
    },
    '/storage-locations': {
      get: {
        tags: ['StorageLocations'],
        summary: 'List storage locations',
        description: 'Returns storage locations',
        parameters: withListParams([
          { name: 'lendingLocationId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/StorageLocation' } }), ...errorResponses },
      },
      post: {
        tags: ['StorageLocations'],
        summary: 'Create storage location',
        description: 'Creates a storage location',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/StorageLocation' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/StorageLocation' }), ...errorResponses },
      },
    },
    '/storage-locations/{id}': {
      get: {
        tags: ['StorageLocations'],
        summary: 'Get storage location',
        description: 'Fetch a storage location by id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/StorageLocation' }), ...errorResponses },
      },
      put: {
        tags: ['StorageLocations'],
        summary: 'Update storage location',
        description: 'Updates a storage location',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/StorageLocation' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/StorageLocation' }), ...errorResponses },
      },
      delete: {
        tags: ['StorageLocations'],
        summary: 'Delete storage location',
        description: 'Deletes a storage location',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/storage-locations/{id}/active': {
      put: {
        tags: ['StorageLocations'],
        summary: 'Set active',
        description: 'Activate or deactivate storage location',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { isActive: { type: 'boolean' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/StorageLocation' }), ...errorResponses },
      },
    },
    '/asset-attachments': {
      get: {
        tags: ['AssetAttachments'],
        summary: 'List attachments',
        description: 'Returns attachments',
        parameters: withListParams([
          { name: 'assetModelId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'assetId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'kind', in: 'query', schema: { type: 'string' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/AssetAttachment' } }), ...errorResponses },
      },
      post: {
        tags: ['AssetAttachments'],
        summary: 'Create attachment',
        description: 'Creates an attachment',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetAttachment' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetAttachment' }), ...errorResponses },
      },
    },
    '/asset-attachments/{id}': {
      get: {
        tags: ['AssetAttachments'],
        summary: 'Get attachment',
        description: 'Fetch an attachment',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetAttachment' }), ...errorResponses },
      },
      put: {
        tags: ['AssetAttachments'],
        summary: 'Update attachment',
        description: 'Updates an attachment',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetAttachment' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetAttachment' }), ...errorResponses },
      },
      delete: {
        tags: ['AssetAttachments'],
        summary: 'Delete attachment',
        description: 'Deletes an attachment',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/asset-maintenance': {
      get: {
        tags: ['AssetMaintenance'],
        summary: 'List maintenance',
        description: 'Returns maintenance records',
        parameters: withListParams([
          { name: 'assetId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'status', in: 'query', schema: { type: 'string' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/AssetMaintenance' } }), ...errorResponses },
      },
      post: {
        tags: ['AssetMaintenance'],
        summary: 'Create maintenance',
        description: 'Creates a maintenance record',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetMaintenance' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetMaintenance' }), ...errorResponses },
      },
    },
    '/asset-maintenance/{id}': {
      get: {
        tags: ['AssetMaintenance'],
        summary: 'Get maintenance',
        description: 'Fetch a maintenance record',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetMaintenance' }), ...errorResponses },
      },
      put: {
        tags: ['AssetMaintenance'],
        summary: 'Update maintenance',
        description: 'Updates a maintenance record',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AssetMaintenance' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetMaintenance' }), ...errorResponses },
      },
      delete: {
        tags: ['AssetMaintenance'],
        summary: 'Delete maintenance',
        description: 'Deletes a maintenance record',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/asset-maintenance/{id}/complete': {
      put: {
        tags: ['AssetMaintenance'],
        summary: 'Complete maintenance',
        description: 'Marks maintenance as completed',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { completedAt: { type: 'string', format: 'date-time' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AssetMaintenance' }), ...errorResponses },
      },
    },
    '/custom-field-definitions': {
      post: {
        tags: ['CustomFieldDefinitions'],
        summary: 'Create custom field definition',
        description: 'Creates a custom field definition',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/CustomFieldDefinition' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/CustomFieldDefinition' }), ...errorResponses },
      },
    },
    '/custom-field-definitions/{id}': {
      get: {
        tags: ['CustomFieldDefinitions'],
        summary: 'Get custom field definition',
        description: 'Fetch a custom field definition',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/CustomFieldDefinition' }), ...errorResponses },
      },
      put: {
        tags: ['CustomFieldDefinitions'],
        summary: 'Update custom field definition',
        description: 'Updates a custom field definition',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/CustomFieldDefinition' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/CustomFieldDefinition' }), ...errorResponses },
      },
      delete: {
        tags: ['CustomFieldDefinitions'],
        summary: 'Delete custom field definition',
        description: 'Deletes a custom field definition',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/custom-field-definitions/{id}/deactivate': {
      put: {
        tags: ['CustomFieldDefinitions'],
        summary: 'Deactivate custom field definition',
        description: 'Deactivates a custom field definition',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/CustomFieldDefinition' }), ...errorResponses },
      },
    },
    '/custom-field-definitions/asset-model/{assetModelId}': {
      get: {
        tags: ['CustomFieldDefinitions'],
        summary: 'List by asset model',
        description: 'List custom fields for an asset model',
        parameters: withListParams([{ name: 'assetModelId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/CustomFieldDefinition' } }), ...errorResponses },
      },
    },
    '/custom-field-definitions/lending-location/{lendingLocationId}': {
      get: {
        tags: ['CustomFieldDefinitions'],
        summary: 'List by lending location',
        description: 'List custom fields for a lending location',
        parameters: withListParams([{ name: 'lendingLocationId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/CustomFieldDefinition' } }), ...errorResponses },
      },
    },
    '/custom-field-definitions/asset-instance/{assetInstanceId}/resolve': {
      get: {
        tags: ['CustomFieldDefinitions'],
        summary: 'Resolve for asset instance',
        description: 'Resolves custom fields for an asset instance',
        parameters: [{ name: 'assetInstanceId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/CustomFieldDefinition' } }), ...errorResponses },
      },
    },
    '/custom-field-values/{assetInstanceId}': {
      get: {
        tags: ['CustomFieldValues'],
        summary: 'List custom field values',
        description: 'List values for an asset instance',
        parameters: withListParams([{ name: 'assetInstanceId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/CustomFieldValue' } }), ...errorResponses },
      },
    },
    '/custom-field-values/{assetInstanceId}/{customFieldDefinitionId}': {
      put: {
        tags: ['CustomFieldValues'],
        summary: 'Set custom field value',
        description: 'Sets a custom field value for an asset instance',
        parameters: withIdempotency([
          { name: 'assetInstanceId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
          { name: 'customFieldDefinitionId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
        ]),
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { value: { type: 'string' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/CustomFieldValue' }), ...errorResponses },
      },
      delete: {
        tags: ['CustomFieldValues'],
        summary: 'Delete custom field value',
        description: 'Deletes a custom field value',
        parameters: withIdempotency([
          { name: 'assetInstanceId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
          { name: 'customFieldDefinitionId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/loans': {
      get: {
        tags: ['Loans'],
        summary: 'List loans',
        description: 'Returns all loans',
        parameters: withListParams([
          { name: 'userId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'lendingLocationId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'status', in: 'query', schema: { type: 'string' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/Loan' } }), ...errorResponses },
      },
      post: {
        tags: ['Loans'],
        summary: 'Create reservation',
        description: 'Creates a loan reservation',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Loan' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Loan' }), ...errorResponses },
      },
    },
    '/loans/{id}': {
      get: {
        tags: ['Loans'],
        summary: 'Get loan',
        description: 'Fetch a loan by id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Loan' }), ...errorResponses },
      },
      delete: {
        tags: ['Loans'],
        summary: 'Delete loan',
        description: 'Deletes a loan',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/loans/{id}/cancel': {
      post: {
        tags: ['Loans'],
        summary: 'Cancel loan',
        description: 'Cancels a reservation',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: false, content: { 'application/json': { schema: { type: 'object', properties: { userId: { type: 'string', format: 'uuid' }, note: { type: 'string' } } } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Loan' }), ...errorResponses },
      },
    },
    '/loans/{id}/hand-over': {
      post: {
        tags: ['Loans'],
        summary: 'Hand over loan',
        description: 'Marks a loan as handed over',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: false, content: { 'application/json': { schema: { type: 'object' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Loan' }), ...errorResponses },
      },
    },
    '/loans/{id}/return': {
      post: {
        tags: ['Loans'],
        summary: 'Return loan',
        description: 'Marks a loan as returned',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: false, content: { 'application/json': { schema: { type: 'object' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Loan' }), ...errorResponses },
      },
    },
    '/loans/{id}/overdue': {
      post: {
        tags: ['Loans'],
        summary: 'Mark overdue',
        description: 'Marks a loan as overdue',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/Loan' }), ...errorResponses },
      },
    },
    '/loan-items': {
      get: {
        tags: ['LoanItems'],
        summary: 'List loan items',
        description: 'Returns loan items',
        parameters: withListParams([
          { name: 'loanId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'assetId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'status', in: 'query', schema: { type: 'string' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/LoanItem' } }), ...errorResponses },
      },
      post: {
        tags: ['LoanItems'],
        summary: 'Add item',
        description: 'Adds an item to a loan',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoanItem' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LoanItem' }), ...errorResponses },
      },
    },
    '/loan-items/{id}': {
      get: {
        tags: ['LoanItems'],
        summary: 'Get loan item',
        description: 'Fetch a loan item',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LoanItem' }), ...errorResponses },
      },
      put: {
        tags: ['LoanItems'],
        summary: 'Update loan item',
        description: 'Updates a loan item',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoanItem' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LoanItem' }), ...errorResponses },
      },
      delete: {
        tags: ['LoanItems'],
        summary: 'Delete loan item',
        description: 'Deletes a loan item',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/loan-items/{id}/remove-from-loan': {
      post: {
        tags: ['LoanItems'],
        summary: 'Remove item from loan',
        description: 'Removes an item from a loan',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/loan-signatures': {
      get: {
        tags: ['LoanSignatures'],
        summary: 'List signatures',
        description: 'Returns loan signatures',
        parameters: withListParams([
          { name: 'loanId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'userId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'signatureType', in: 'query', schema: { type: 'string' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/LoanSignature' } }), ...errorResponses },
      },
      post: {
        tags: ['LoanSignatures'],
        summary: 'Create signature',
        description: 'Creates a loan signature',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoanSignature' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LoanSignature' }), ...errorResponses },
      },
    },
    '/loan-signatures/{id}': {
      get: {
        tags: ['LoanSignatures'],
        summary: 'Get signature',
        description: 'Fetch a loan signature',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LoanSignature' }), ...errorResponses },
      },
      put: {
        tags: ['LoanSignatures'],
        summary: 'Update signature',
        description: 'Updates a loan signature',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoanSignature' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LoanSignature' }), ...errorResponses },
      },
      delete: {
        tags: ['LoanSignatures'],
        summary: 'Delete signature',
        description: 'Deletes a loan signature',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/loan-events': {
      get: {
        tags: ['LoanEvents'],
        summary: 'List loan events',
        description: 'Returns loan events',
        parameters: withListParams([
          { name: 'loanId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'userId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'type', in: 'query', schema: { type: 'string' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/LoanEvent' } }), ...errorResponses },
      },
      post: {
        tags: ['LoanEvents'],
        summary: 'Create loan event',
        description: 'Creates a loan event',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoanEvent' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LoanEvent' }), ...errorResponses },
      },
    },
    '/loan-events/{id}': {
      get: {
        tags: ['LoanEvents'],
        summary: 'Get loan event',
        description: 'Fetch a loan event',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LoanEvent' }), ...errorResponses },
      },
      put: {
        tags: ['LoanEvents'],
        summary: 'Update loan event',
        description: 'Updates a loan event',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoanEvent' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/LoanEvent' }), ...errorResponses },
      },
      delete: {
        tags: ['LoanEvents'],
        summary: 'Delete loan event',
        description: 'Deletes a loan event',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/audit-logs': {
      get: {
        tags: ['AuditLogs'],
        summary: 'List audit logs',
        description: 'Returns audit logs',
        parameters: withListParams([
          { name: 'userId', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'entity', in: 'query', schema: { type: 'string' } },
          { name: 'entityId', in: 'query', schema: { type: 'string', format: 'uuid' } },
        ]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'array', items: { $ref: '#/components/schemas/AuditLog' } }), ...errorResponses },
      },
      post: {
        tags: ['AuditLogs'],
        summary: 'Create audit log',
        description: 'Creates an audit log entry',
        parameters: withIdempotency(),
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AuditLog' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AuditLog' }), ...errorResponses },
      },
    },
    '/audit-logs/{id}': {
      get: {
        tags: ['AuditLogs'],
        summary: 'Get audit log',
        description: 'Fetch an audit log',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ $ref: '#/components/schemas/AuditLog' }), ...errorResponses },
      },
      delete: {
        tags: ['AuditLogs'],
        summary: 'Delete audit log',
        description: 'Deletes an audit log',
        parameters: withIdempotencyAndIfMatch([{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }]),
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object' }), ...errorResponses },
      },
    },
    '/authz/check': {
      post: {
        tags: ['Authz'],
        summary: 'Check permission',
        description: 'Checks if user roles include a permission',
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object' } } } },
        security: [{ SessionAuth: [] }],
        responses: { 200: okResponse({ type: 'object', properties: { allowed: { type: 'boolean' } } }), ...errorResponses },
      },
    },
  };
};
